# https://github.com/bitnami/charts/tree/main/bitnami/postgresql#parameters
# https://hub.docker.com/r/bitnamicharts/postgresql/tags
image:
  tag: "17.2.0-debian-12-r6"
  pullPolicy: "IfNotPresent"
  debug: true
# the service name, if not set, defaults to {{ Release.Name }}-{{ Chart.Name }}
fullnameOverride: postgres
architecture: standalone
auth:
  existingSecret: postgres
  secretKeys:
    adminPasswordKey: postgres-password
primary:
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
  service:
    type: NodePort
    nodePorts:
      postgresql: 30000
  persistence:
    enabled: true
    size: "512Gi"
  initdb:
    user: postgres
    scriptsSecret: postgres-initdb
  extendedConfiguration: |-
    # Memory Configuration
    shared_buffers = 1GB
    effective_cache_size = 3GB
    work_mem = 102MB
    maintenance_work_mem = 205MB

    # Checkpoint Related Configuration
    min_wal_size = 2GB
    max_wal_size = 3GB
    checkpoint_completion_target = 0.9
    wal_buffers = -1

    # Network Related Configuration
    listen_addresses = '*'
    max_connections = 64

    # Storage Configuration
    random_page_cost = 1.1
    effective_io_concurrency = 200

    # Worker Processes Configuration
    max_worker_processes = 8
    max_parallel_workers_per_gather = 2
    max_parallel_workers = 2

    # Logging configuration for pgbadger
    logging_collector = on
    log_checkpoints = on
    log_connections = on
    log_disconnections = on
    log_lock_waits = on
    log_temp_files = 0
    lc_messages = 'C'

    # Adjust the minimum time to collect the data
    log_min_duration_statement = '10s'
    log_autovacuum_min_duration = 0

    # CSV Configuration
    log_destination = 'csvlog'